pipeline {
    agent any
    
    stages {
        stage("Build") {
            steps {
                echo "Building"
                bat "ng build"
            }
        }

        stage("Unit & Integration tests") {
            steps {
                echo "Unit & Integration tests"
                bat "ng test --progress=false --watch=false --browsers=ChromeHeadless"
            }
        }
    }
}
